version: '3'
services:
 web:
  build: .
  container_name: ManageLdap
  restart: always
  hostname: 'manage.supercompta.com'
  labels:
   - "traefik.enable=true"
   - "traefik.docker.network=traefik_network"
   - "traefik.http.routers.ManageLdap-secure.entrypoints=traefik_network_secure"
   - "traefik.http.routers.ManageLdap-secure.rule=Host(`manage.supercompta.com`)"
   - "traefik.http.routers.ManageLdap-secure.service=ManageLdap-service"
   - "traefik.http.services.ManageLdap-service.loadbalancer.server.port=80"

  networks:
   - traefik_network

networks:
 traefik_network:
  external: true

