---

- name: "reload_firewall"
  command: "firewall-cmd --reload"

- name: "restart_systemd"
  command: "systemctl restart systemd-resolved"

- name: "restart_all_services"
  systemd:
    enabled: yes
    state: started
    name: "{{ item }}" # Boucle sur les services juste après
  with_items:
    - samba.service
    - systemd-resolved.service


