version: "3"

services:
 mariadb:
  image: mariadb:latest
  container_name: nextcloud-db
  volumes:
   - nextcloud-db-data:/var/lib/mysql
  networks:
   - default
  restart: always
  environment:
   TZ: CET
   MYSQL_ROOT_PASSWORD: supersecretpassword
   MYSQL_DATABASE: db
   MYSQL_USER: dbuser
   MYSQL_PASSWORD: dbpassword

 redis:
  image: redis:latest
  container_name: nextcloud-redis
  restart: always
  networks:
   - default
  volumes:
   - redis:/var/lib/redis

 nextcloud:
  depends_on:
   - redis
   - mariadb
  image: nextcloud:latest 
  container_name: nextcloud
  hostname: 'nextcloud.supercompta.com'
  volumes:
   - ./files:/var/www/html
  networks:
   - traefik_network
   - default
  restart: always
  labels:
   - "traefik.enable=true"
   - "traefik.docker.network=traefik_network"
   - "traefik.http.routers.nextcloud-secure.entrypoints=traefik_network_secure"
   - "traefik.http.routers.nextcloud-secure.rule=Host(`nextcloud.supercompta.com`)"
   - "traefik.http.routers.nextcloud-secure.service=nextcloud-service"
   - "traefik.http.services.nextcloud-service.loadbalancer.server.port=80"
  environment:
   REDIS_HOST: redis
   MYSQL_HOST: db:3306
   MYSQL_DATABASE: db
   MYSQL_USER: dbuser
   MYSQL_PASSWORD: dbpassword

networks:
 traefik_network:
  external: true
    
volumes:
 nextcloud-db-data:
 redis:
